config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :members do
    collection do
      get 'unconfirmed'
      get 'confirmation'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/committee.rb
class Committee < ApplicationRecord
  has_many :members
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :members
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :room, optional: true
  belongs_to :committee, optional: true
  belongs_to :department, optional: true

  validates :name, presence: true

  default_scope { order :room_id, :department_id, :committee_id }

  before_save do
    MailingListMailer.add_address(mail_address).deliver
  end

  before_update do
    MailingListMailer.bye_address(mail_address_was).deliver if mail_address_changed?
  end

  before_destroy do
    MailingListMailer.bye_address(mail_address).deliver
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :members, dependent: :restrict_with_exception
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_menu

  private

  def set_menu
    @menu_rooms = Room.all
    @menu_departments = Department.all
    @menu_committees = Committee.all
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_room, only: [:index]
  before_action :set_department, only: [:index]
  before_action :set_committee, only: [:index]
  before_action :build_member, only: [:create]
  before_action :set_member, only: [:edit, :destroy, :update]
  before_action :set_form_properties, only: [:edit, :new, :create]

  def index
    group = [
      @room&.members,
      @department&.members,
      @committee&.members,
      Member.all
    ].find { |g| g.present? }
    @members = group.eager_load :department, :committee, :room
  end

  def unconfirmed
    @members = Member.where(sent_confirmed: false)
    render template: 'members/index'
  end

  def edit
  end

  def destroy
    @member.destroy
    redirect_to action: :index
  end

  def update
    @member.attributes = properties_params
    @member.mail_address = '' unless properties_params.key?(:mail_address)
    if @member.save
      redirect_to action: :index
    else
      render :edit
    end
  end

  def new
    @member = Member.new()
  end

  def create
  	if @member.save
  	  redirect_to action: :index
    else
      render :new
    end
  end

  def confirmation
    timestamp = Time.zone.today.strftime('%Y-%m-%d')

    ConfirmationMailer.send_mailing_list(timestamp).deliver
    Member.where(sent_confirmed: false).each do |member|
      ConfirmationMailer.confirm(member, timestamp).deliver if member.mail_address != ''
    end

    redirect_to action: :index
  end

  private

  # before_action
  def set_member
  	@member = Member.find(id_params[:id])
  end

  def build_member
  	@member = Member.new(properties_params)
  end

  def set_room
    @room = Room.find_by(id: room_params[:room_id])
  end

  def set_department
    @department = Department.find_by(id: department_params[:department_id])
  end

  def set_committee
    @committee = Committee.find_by(id: committee_params[:committee_id])
  end

  def set_form_properties
    @departments = Department.all
    @committees = Committee.all
    @rooms = Room.all
  end

  # strong parameters
  def id_params
  	params.permit(:id)
  end

  def properties_params
  	params
      .require(:member)
  	  .permit(
  	  	:name,
  	  	:room_id,
  	  	:department_id,
  	  	:committee_id,
  	  	:phone_number,
  	  	:mail_address,
        :is_absent,
        :sent_confirmed,
  	  )
  end

  def room_params
    params.permit(:room_id)
  end

  def department_params
    params.permit(:department_id)
  end

  def committee_params
    params.permit(:committee_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def belongs_name
    if @room.present?
      @room.name + "の"
    elsif @department.present?
      @department.name + "部会の"
    elsif @committee.present?
      @committee.name + "委員会の"
    else
      ""
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "B12名簿" %></title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'B12名簿', { :controller => :members, :action => :index }, :class => 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">部屋 <span class="caret"></span></a>
							<ul class="dropdown-menu">
              <% for room in @menu_rooms %>
                <li><%= link_to room.name, { :controller => :members, :action => :index, :room_id => room.id } %><li>
              <% end %>
							</ul>
						</li>
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">部会 <span class="caret"></span></a>
							<ul class="dropdown-menu">
              <% for department in @menu_departments %>
                <li><%= link_to department.name, { :controller => :members, :action => :index, :department_id => department.id } %></li>
              <% end %>
							</ul>
						</li>
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">委員会 <span class="caret"></span></a>
							<ul class="dropdown-menu">
              <% for committee in @menu_committees %>
                <li><%= link_to committee.name, { :controller => :members, :action => :index, :committee_id => committee.id } %></li>
              <% end %>
							</ul>
						</li>
          </ul>
          <div class='navbar-right navbar-text'>
            <%=
              link_to "メーリスが届いてない人に勧告メールを送る",
                      { controller: 'members', action: 'confirmation' },
                      { data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } }
            %>
          </div>
        </div>
      </div>
    </div>
    <div class="container">

      <div class="row">
<!--
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>索引</h3>
            <ul class="nav nav-list">
              <li class="nav-header">部会</li>
              <li class="nav-header">委員会</li>
              <li class="nav-header">部屋</li>
            </ul>
          </div>
        </div>
-->
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div> <!-- /row -->

      <footer class="footer">
        <p class="text-muted">&copy; Kumano B12 2016</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => "form-horizontal member" } do |f| %>

  <% if @member.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@member.errors.count, "つのエラー") %> が原因で登録できませんでした</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :room_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :room_id, @rooms.pluck(:name, :id), {:include_blank => true}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:room_id) %>
  </div>
  <div class="form-group">
    <%= f.label :department_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :department_id, @departments.pluck(:name, :id), {:include_blank => true}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:department_id) %>
  </div>
  <div class="form-group">
    <%= f.label :committee_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:committee_id, @committees.pluck(:name, :id), {:include_blank => true}, {:class => 'form-control'}) %>
    </div>
    <%=f.error_span(:committee_id) %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone_number, :class => 'form-control', :type => 'tel' %>
    </div>
    <%=f.error_span(:phone_number) %>
  </div>
  <div class="form-group">
    <%= f.label :mail_address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mail_address, :class => 'form-control', :type => 'email' %>
    </div>
    <%=f.error_span(:mail_address) %>
  </div>
  <div class="form-group">
    <%= f.label :is_absent, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <label><%= f.radio_button :is_absent, true, :class => 'form-control' %>休寮中</label>
      <label><%= f.radio_button :is_absent, false, :class => 'form-control' %>在寮中</label>
    </div>
    <%=f.error_span(:is_absent) %>
  </div>
  <div class="form-group">
    <%= f.label :sent_confirmed, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <label><%= f.radio_button :sent_confirmed, true, :class => 'form-control' %>確認済</label>
      <label><%= f.radio_button :sent_confirmed, false, :class => 'form-control' %>未確認</label>
    </div>
    <%=f.error_span(:is_absent) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1>
    <%= belongs_name %><%=t '.title', :default => model_class.model_name.human %>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_member_path, class: 'btn btn-primary' %>
    <%= link_to "メーリスが届いてない人達", { action: 'unconfirmed' }, { class: 'btn btn-danger' } %>
  </h1>
</div>
<div style="text-align:right">
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:room_id) %></th>
      <th><%= model_class.human_attribute_name(:department_id) %></th>
      <th><%= model_class.human_attribute_name(:committee_id) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:mail_address) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><b><%= member.name %></b></td>
        <td><%= member.room&.name %></td>
        <td><%= member.department&.name %></td>
        <td><%= member.committee&.name %></td>
        <td><input type="text" size="14" readonly='readonly' value="<%= member.phone_number %>"></td>
        <td><input type="text" size="40" readonly='readonly' value="<%= member.mail_address %>"></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-success' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>